export type ErrorCode =
  | 'OK'
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'VALIDATION_ERROR'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'TOO_MANY_REQUESTS'
  | 'EMAIL_SEND_FAILED'
  | 'PLAN_GENERATION_FAILED'
  | 'AI_TIMEOUT'
  | 'AI_SAFETY_BLOCKED'
  | 'INTERNAL_ERROR';